### ISSUE TITLE
Instructions 

### ISSUE THREAD

**Issue by Nismonx** [MTrab/vector#1]
I understand this is early development but finaly sourced a second RPi to test your work. 😊
Would it be possible to add some basic instructions plz?

many thanks 

Edited:
Fantastic work BTW

**Comment by MTrab** [comment]
Haven't had the time to do any development in a long time, so not sure how much still works

**Comment by NonaSuomy** [comment]
I believe in you!

**Comment by NonaSuomy** [comment]
With the new piper/whisper stuff in HA beta .5 would it be easier to get this stuff more stable?

**Comment by MTrab** [comment]
Haven't had the time to look into that - and have no time for this integration as it is right now. Have 2 other integrations that take up all my spare time for coding.

So do not expect any progress in this integration in near future.

**Comment by NonaSuomy** [comment]
Where are the instructions?

**Comment by MTrab** [comment]
Nowhere as this is a dead project.
